<?php
include '../../lib/base/Bootstrap.php';
Bootstrap::boot();

/*
	file in.txt should contain the output generated by PHP Insights for the issues PhpCsFixer\Fixer\FunctionNotation\VoidReturnFixer
*/
$current_file = null;
$from = null;
$to = null;
foreach(file("../../in.txt") as $line) {
	if (strpos($line, '.php: ') !== false) {
		$current_file = '../../' . trim(str_replace(':', '', $line));
	}
	if (strpos($line, '-') === 0) {
		$from = substr($line, 1);
		$from = trim($from);
	}
	if (strpos($line, '+') === 0) {
		$to = substr($line, 1);
		$to = trim($to);
		printf("[%s]\n", $current_file);
		printf("FROM: <%s>\n", $from);
		printf("TO: <%s>\n", $to);
		$content = file_get_contents($current_file);
		$content = str_replace($from, $to, $content);
		file_put_contents($current_file, $content);
	}
}