include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - quality

lint:
  stage: quality
  image:
    name: php:7.4-cli
  script:
    - shopt -s globstar
    - set -e
    - for x in **/*.php; do php -l "$x"; done

code_quality:
  stage: quality
  image:
    name: nunomaduro/phpinsights
    entrypoint: [""]
  script: /usr/bin/phpinsights --min-quality=37 --min-complexity=15 --min-architecture=52 --min-style=31 --no-interaction --config-path=util/bin/insights.php --format=codeclimate > codeclimate-report.json
  artifacts:
    paths:
      - "./codeclimate-report.json"
    reports:
      codequality: codeclimate-report.json
